import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { ARCHETYPES, ARCHETYPE_LABEL, ARCHETYPE_BLURB, ARCHETYPE_COLOR } from "../src/lib/token-economy";
import { ATTRIBUTE_META } from "../src/lib/rpg-attributes";

const OUTPUT_FILE = join(process.cwd(), "TKC_Project_Intelligence.md");

function generateMarkdown() {
  let md = `# TKC Talent Support Dashboard: Project Intelligence\n\n`;
  md += `> [!NOTE]\n`;
  md += `> This document is automatically generated by the Antigravity agent. It contains the current business logic, schemas, and architectural metaphors of the TKC Digital Twin (v3.4 Septet).\n\n`;

  md += `## 1. Architectural Metaphor\n`;
  md += `- **ROM Chip**: The Next.js application core.\n`;
  md += `- **Battery-Backed RAM**: The Neon PostgreSQL database (Source of Truth).\n`;
  md += `- **Memory Card**: Google Sheets mirror (Shadow record for humans).\n`;
  md += `- **The Abbey**: Alltrades Abbey (vocation change system).\n\n`;

  md += `## 2. Archetypes (The Septet)\n`;
  md += `The system currently supports 7 archetypes based on Dragon Quest III Famicom (1988) vocations.\n\n`;
  md += `| Vocation | Identity | Color | Blurb |\n`;
  md += `| :--- | :--- | :--- | :--- |\n`;

  for (const arch of ARCHETYPES) {
    md += `| **${ARCHETYPE_LABEL[arch]}** | \`${arch}\` | \`${ARCHETYPE_COLOR[arch]}\` | ${ARCHETYPE_BLURB[arch]} |\n`;
  }
  md += `\n`;

  md += `## 3. RPG Attribute Mapping\n`;
  md += `We map workplace psychology metrics to classic RPG attributes.\n\n`;
  md += `| Attribute | Meaning | Icon | Description |\n`;
  md += `| :--- | :--- | :--- | :--- |\n`;

  for (const [key, meta] of Object.entries(ATTRIBUTE_META)) {
    md += `| **${meta.label}** | ${meta.meaning} | ${meta.icon} | ${meta.meaningTh} |\n`;
  }
  md += `\n`;

  md += `## 4. Database Schema Summary\n`;
  md += `### Core Tables\n`;
  md += `- \`employees\`: Master roster.\n`;
  md += `- \`employee_attributes\`: Live RPG stats and forced vocations.\n`;
  md += `- \`vocation_changes\`: Append-only ledger of Alltrades Abbey rituals.\n`;
  md += `- \`attendance_log\`: [NEW v3.4] Lobby check-in/out records.\n`;
  md += `- \`interactions\`: [NEW v3.4] Proximity-based chat logs.\n\n`;

  md += `## 5. The "Sacred Rule"\n`;
  md += `> [!IMPORTANT]\n`;
  md += `> **All state-change paths MUST write to Postgres AND fire a fire-and-forget mirror call to Google Sheets.**\n\n`;

  md += `--- \n*Last updated: ${new Date().toLocaleString('en-TH', { timeZone: 'Asia/Bangkok' })}*\n`;

  writeFileSync(OUTPUT_FILE, md);
  console.log(`Successfully exported intelligence to ${OUTPUT_FILE}`);
}

generateMarkdown();
